### ISSUE TITLE
BUG? Cannot undo move

### ISSUE THREAD

**Issue by richardlm** [GitMurf/obsidian-drag-and-drop-blocks#12]
(Windows) After carrying out the drag block operation, using CTRL-Z will highlight the new block, then anther CTRL-Z will delete the new block. But the next CTRL-Z does not replace the block back in its original page. 

This is thus a one-way, non-reversible operation.

Can this be fixed, or is there another way to reverse the operation?

**Comment by hieu6** [comment]
Try using ctrl+Z+Shift to redo the undo

**Comment by richardlm** [comment]
I can see that correcting the attempt at a correction, but it doesn't help me get the original block back in its original position.

However, I have now worked out what is necessary - having used CTRL-Z twice to remove the block from the new page it is necessary to click in the original page to make it the focus. Then CTRL-Z replaces the original block.

**Comment by GitMurf** [comment]
Yes, obsidian handles Undo per pane.
