### ISSUE TITLE
Does not appear to be working at all

### ISSUE THREAD

**Issue by danrthompson** [GitMurf/obsidian-drag-and-drop-blocks#36]
I am not sure if this is just me, but right now the plugin does not seem to be functional.

I can see the handles in the gutter, but when I click and drag them, nothing happens. I cannot actually even drag the handle at all, even though the icon for the handle does appear in the gutter.

I have tried uninstalling all other plugins, but to no avail.

I just installed this recently, and I wonder if there is a breaking change to the API. I've tried downgrading this plugin to previous versions, but unfortunately that did not help either.

I've tried dragging without modifiers, using alt, using shift, using others, nothing makes a difference.

I'm on a Mac, and I'm on Obsidian version 0.16.2 (installer version 0.14.15).

When I turn on the developer tools, I do see two errors related to this plugin. Two packages are marked as deprecated. Unsure if they are the cause or not. I am unable to trigger any other error messages, as when I try to drag and drop blocks by grabbing the handles for a list, nothing happens (including no error in the developer console). The two error messages for the deprecated packages are:

```
Error: [CM6][obsidian-drag-n-drop-plugin] Using a deprecated package: "@codemirror/gutter".
See the stack trace to find the faulty plugin and file an issue with the plugin author. 
Details: https://discuss.codemirror.net/t/release-0-20-0/4302
    at o (app.js:1:1033613)
    at anonymous (plugin:obsidian-drag-n-drop-plugin:5586:32)
    at e.<anonymous> (app.js:1:1033908)
    at app.js:1:235237
    at Object.next (app.js:1:235342)
    at a (app.js:1:234081)
o @ app.js:1
```

And second deprecated package:
```
Error: [CM6][obsidian-drag-n-drop-plugin] Using a deprecated package: "@codemirror/rangeset".
See the stack trace to find the faulty plugin and file an issue with the plugin author. 
Details: https://discuss.codemirror.net/t/release-0-20-0/4302
    at o (app.js:1:1033613)
    at anonymous (plugin:obsidian-drag-n-drop-plugin:10928:34)
    at e.<anonymous> (app.js:1:1033908)
    at app.js:1:235237
    at Object.next (app.js:1:235342)
    at a (app.js:1:234081)
o @ app.js:1
```

Please let me know if I can help in any way by providing additional information or testing anything. I would be thrilled to get this to work, because I absolutely miss this feature of Roam a lot and would love to be able to use it in Obsidian :). So thanks very much for creating this plugin, and I hope it can get back to working soon!

**Comment by GitMurf** [comment]
@danrthompson I apologize but this Plugin is no longer under development. Obsidian substantially switched their under the hood editor which drives the entire app from CodeMirror 5 to CodeMirror 6 which basically changes everything you do in trying to integrate with it. So this plugin would have to be re-written more or less from scratch to work with CM6. Some day I may pick it back up but for now this Plugin is considered deprecated and no longer under development. I will update the README to make that clear. Sorry for the bad news!

**Comment by danrthompson** [comment]
Argh! Im sad to hear that but I totally understand and thanks for the update (and for making such an awesome plug-in! Totally fair to not have the time to do it for the second time haha)

**Comment by danrthompson** [comment]
Oh actually it looks like there is a fork that is under active development. It currently is also broken but the author just replied to the issue I wrote and said that he is confident he’ll be able to get it to work after he gets the new release. It sounds like he already did the migration to CodeMirror 6.

Anyway I just wanted to mention that in case you want to redirect people to the new plug-in in the readme :).

Here is a link: https://github.com/artem-barmin/obsidian-block-drag-n-drop

Thanks again
