### ISSUE TITLE
Dragging from search pane to page

### ISSUE THREAD

**Issue by crazymedguy** [GitMurf/obsidian-drag-and-drop-blocks#5]
An example of what it normally does and what I'd love it be like...

![screencap](https://user-images.githubusercontent.com/67627057/131081827-51a3495b-fe3a-4fd4-b727-33c5226e3ff2.gif)

I realised I forgot to put the "!" in front to make it a block ref, but maybe you get what I mean.

**Comment by GitMurf** [comment]
This is now complete with v0.4 release. https://github.com/GitMurf/obsidian-drag-and-drop-blocks/releases/tag/v0.4
