### ISSUE TITLE
Support Code Block Reference

### ISSUE THREAD

**Issue by Quorafind** [GitMurf/obsidian-drag-and-drop-blocks#7]
Is it doable to support code block reference?like

````
 ```code
code
 ```
```

**Comment by GitMurf** [comment]
This is a great idea and I plan to try and handle anything that has multiple lines together in one "block" like code blocks. I will keep you posted. Hopefully in the next week or two.

**Comment by GitMurf** [comment]
This is now complete with v0.4 release. https://github.com/GitMurf/obsidian-drag-and-drop-blocks/releases/tag/v0.4
